parameters:
- name: poolImage
  default: ubuntu-22.04
  displayName: Builder
  type: string
  values:
  - ubuntu-22.04
  - ubuntu-24.04
  - ubuntu-latest
- name: sourceImageSku
  default: 0001-com-ubuntu-minimal-jammy:minimal-22_04-lts-gen2
  displayName: Agent base image
  type: string
  values: # az vm image list-skus --location switzerlandnorth --publisher Canonical --offer ubuntu-26_04-lts | jq '.[].id'
  - custom
  - 0001-com-ubuntu-minimal-jammy:minimal-22_04-lts-gen2
  - 0001-com-ubuntu-server-jammy:22_04-lts-gen2
  - ubuntu-24_04-lts:minimal
  - ubuntu-24_04-lts:server
  - ubuntu-26_04-lts-daily:minimal
  - ubuntu-26_04-lts-daily:server
- name: sourceImageVersion
  default: latest
  displayName: Agent base image version
  type: string
- name: destinationImageVersion
  default: BuildId
  displayName: Agent image Gallery version (e.g. 1.23.450)
  type: string
- name: destinationOsDiskSize
  default: 30
  displayName: Agent OS Disk size in GB
  type: number
  values:
  - 4
  - 8
  - 16
  - 30
  - 32
- name: dockerImagesToCache
  default: none
  displayName: Space separated list of Docker Hub image tags to cache
  type: string
trigger:
- main

jobs:
- job: build
  displayName: Build
  pool:
    vmImage: ${{ parameters.poolImage }}
  steps:
  - task: DownloadSecureFile@1
    displayName: 'Download certificate'
    inputs:
      secureFile: 96134ed7-3fce-4488-a47d-46dd0725d0b0
    name: agentBuilderCertificate
  - task: Bash@3
    displayName: 'Build agent'
    env:
      ARM_CLIENT_CERT_PASSWORD: $(ARM_CLIENT_CERT_PASSWORD)
      ARM_CLIENT_CERT_PATH: $(agentBuilderCertificate.secureFilePath)
      DOCKERHUB_LOGIN: $(DOCKERHUB_LOGIN)
      DOCKERHUB_PAT: $(DOCKERHUB_PAT)
    inputs:
      filePath: ./build-agent.sh
  variables:
  - group: agent-builder-auth
  - group: agent-builder-build
  - name: SOURCE_IMAGE_SKU
    readonly: true
    ${{ if eq(parameters.sourceImageSku, 'custom') }}:
      value: '$(BUILD_CUSTOM_IMAGE_SKU)'
    ${{ else }}:
      value: ${{ parameters.sourceImageSku }}
  - name: SOURCE_IMAGE_VERSION
    readonly: true
    value: ${{ parameters.sourceImageVersion }}
  - name: DESTINATION_IMAGE_STORAGE
    readonly: true
    ${{ if ne(parameters.destinationImageVersion, 'BuildId') }}:
      value: Standard_ZRS
  - name: DESTINATION_IMAGE_VERSION
    readonly: true
    ${{ if eq(parameters.destinationImageVersion, 'BuildId') }}:
      value: '0.0.$(Build.BuildId)'
    ${{ else }}:
      value: ${{ parameters.destinationImageVersion }}
  - name: DESTINATION_OSDISK_SIZE
    readonly: true
    value: ${{ parameters.destinationOsDiskSize }}
  - name: DOCKERHUB_IMAGES
    readonly: true
    ${{ if eq(parameters.dockerImagesToCache, 'none') }}:
      value: ''
    ${{ else }}:
      value: ${{ parameters.dockerImagesToCache }}
